# Generated by Django 5.0.6 on 2024-06-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teboxeo', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='./teboxeo/static/img'),
        ),
    ]
